name: Treinamento

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    
    env:
      #NOME_IMAGEM: testesitecontagem
      NOME_IMAGEM: monteiro476
      NOME_COMPLETO_IMAGEM: ${{ secrets.DOCKER_USERNAME }}/$NOME_IMAGEM

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Teste com Bash
      run: |
        lsb_release -a
        ls
        history

    - name: Teste com Powershel Core
      shell: pwsh
      run: |
        Write-Host "Primeira Mensagem"
        Write-Host "Segunda Mensagem com PowerShell Core"
        
      
    - name: Login no Docker Hub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Exibir nome do Repositorio
      env:
        SAUDACAO: Bem-vindos ao Treinamento!
      run: |
        echo $GITHUB_REPOSITORY
        echo ${{ ENV.saudacao }}

    - name: Build e Push no Docker Hub
      run: |
        cd ./SiteContagem
        docker build . --file Dockerfile --tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest
        docker tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest ${{ env.NOME_COMPLETO_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.NOME_COMPLETO_IMAGEM }}
